services:
  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
    command: npm run start:dev
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV=development

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development