services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
