export const UI_STRINGS = {
  auth: {
    loginHeader: "התחברות למערכת",
    loginDescription: "הזן את שם המשתמש והסיסמה שלך כדי להיכנס",
    loginSubmit: "התחבר למערכת",
    signupHeader: "יצירת חשבון חדש",
    signupDescription: "הצטרף אלינו והתחל לנהל את המלאי שלך בצורה חכמה",
    signupSubmit: "הרשמה למערכת",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    userName: "שם משתמש",
    phone: "טלפון",
    email: "כתובת מייל",
    address: "כתובת",
    password: "סיסמא",
    tz: "תעודת זהות",
    welcomeTitle: "ברוכים הבאים!",
    welcomeDescription: "הצטרף אלינו היום והתחל לנהל את המלאי והמתכונים של העסק שלך בצורה חכמה, מהירה ומקצועית.",
    backTitle: "שמחים שחזרת!",
    backDescription: "התחבר למשתמש שלך כדי להמשיך לנהל את המלאי, המתכונים, ההזמנות ולוח השנה.",
    noAccountYet: "אין לך חשבון עדיין?",
    registerHere: "להרשמה לחץ כאן",
    hasAccountAlready: "כבר יש לך חשבון?",
    loginHere: "להתחברות לחץ כאן",
  },
  companySetup: {
    bannerTitle: "הגדרת העסק שלך",
    bannerDescription: "הזן את פרטי החברה כדי להקים את העסק שלך במערכת ולהתחיל לנהל מלאי, מתכונים ויומן עבודה בצורה חכמה.",
    formTitle: "יצירת חברה חדשה",
    formSubtitle: "מלא את הפרטים הבאים כדי להשלים את ההגדרה",
    companyName: "שם החברה",
    companyIdentifier: "ח.פ. / מזהה חברה",
    companyAddress: "כתובת החברה",
    companyPhone: "טלפון ליצירת קשר",
    submit: "צור חברה והמשך",
  },
  companyPicker: {
    bannerTitle: "החברות שלך",
    bannerDescription: "מקום אחד לנהל את כל העסקים שלך. בחר את החברה שברצונך לעבוד איתה כעת, או הפעל מנוי ממתין.",
    formTitle: "בחירת חברה פעילה",
    formSubtitle: "בחר חברה כדי להמשיך למערכת הניהול",
    enterCompany: "כניסה",
    activeCompaniesHeader: "חברות פעילות",
    pendingCompaniesHeader: "חברות ממתינות להפעלה",
    createNewCompany: "+ הקם חברה חדשה",
    backToHome: "ביטול וחזרה לדף הבית",
  },
  navbar: {
    employeeManagement: "ניהול עובדים",
    logout: "התנתק",
    hello: "שלום,",
  },
  home: {
    welcomePrefix: "שלום,",
    activeCompanyPrefix: "חברה פעילה:",
    welcomeDescription: "ברוך הבא למערכת ניהול המלאי החכמה של העסק שלך.",
    shortcutsHeader: "קיצורי דרך מהירים",
    recipesTitle: "ספר המתכונים",
    calendarTitle: "לוח שנה ואירועים",
    preparationsTitle: "השלמת הכנות",
    rawMaterialsTitle: "חומרי גלם",
    reportsTitle: "דוחות ייצור",
    activityLogTitle: "יומן פעולות",
    employeesTitle: "ניהול עובדים",
  },
  employees: {
    pageTitle: "ניהול עובדי חברה",
    activeCompanyPrefix: "חברה פעילה:",
    registerNewEmployee: "רישום עובד חדש",
    roleLabel: "תפקיד במערכת",
    addEmployee: "הוסף עובד",
    searchPlaceholder: "הקלד שם משתמש, שם פרטי או אימייל...",
    searchTzOrUsername: "שם משתמש או תעודת זהות",
    roleEditor: "עובד (Editor)",
  },
  roles: {
    owner: "בעלים",
    admin: "מנהל חברה",
    editor: "עובד",
    viewer: "צופה",
  } as Record<string, string>,
  preparations: {
    pageTitle: "השלמת כמויות הכנה",
    pageSubtitle: "הכנות מוצרים שבוצעו ללא הזנת כמות יציאה בפועל. הזן כמויות כדי לעדכן את המלאי בהתאם.",
    searchPlaceholder: "חפש לפי שם מתכון...",
    loadError: "שגיאה בטעינת ההכנות הממתינות. נא לנסות שנית.",
    invalidVolumeError: "נא להזין כמות תקינה הגדולה מ-0",
    saveError: "שגיאה בשמירת הכמות. נא לנסות שנית.",
    emptyStateTitle: "אין הכנות להשלמה!",
    emptyStateSubtitle: "כל כמויות היציאה של ההכנות שלך מעודכנות במערכת בצורה מלאה. עבודה מצוינת!",
    untitledRecipe: "מתכון ללא שם",
    yieldTypePrefix: "סוג תוצר: ",
    dateTimeLabel: "תאריך ושעה:",
    batchesLabel: "כמות הכפלה (Batches):",
    saveSuccess: "הכמות נשמרה בהצלחה!",
    saveButton: "שמור",
  },
};

