FROM node:18-alpine

WORKDIR /app/front

COPY package*.json ./
RUN npm install

COPY . ./

ARG VITE_BACK
ENV VITE_BACK=$VITE_BACK

RUN npm run build
RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
